name: interleave
description: A library that helps to interleave lists, being possible to personalize the steps and offset.
version: 0.1.0
repository: https://github.com/Paitomax/interleave

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
